#!/usr/bin/python3

import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('127.0.0.1',username='raymond',password='10.paint$RAY.01')
stdin, stdout, stderr = ssh.exec_command("uptime")
type(stdin)
